---
- name: Setup NFS Mounts on Labeler Machines
  hosts: labeler-machines
  become: true
  
  tasks:
    # Load role variables (contains nfs_mounts configuration)
    - name: Load svwi-labelers variables
      ansible.builtin.include_vars:
        file: roles/svwi-labelers/vars/main.yml
    
    - name: Load svwi-labelers defaults
      ansible.builtin.include_vars:
        file: roles/svwi-labelers/defaults/main.yml
    
    - name: Display NFS mounts to be configured
      ansible.builtin.debug:
        msg: "Configuring {{ nfs_mounts | length }} NFS mounts on {{ inventory_hostname }}"
    
    # Run the NFS setup tasks
    - name: Setup NFS mounts
      ansible.builtin.include_tasks:
        file: roles/svwi-labelers/tasks/nfs_setup.yml
    
    # Verify mounts
    - name: Verify NFS mounts are active
      ansible.builtin.shell:
        cmd: df -h | grep -E '/auto/(shared|ds)'
      register: mount_check
      changed_when: false
      failed_when: false
    
    - name: Display mounted filesystems
      ansible.builtin.debug:
        msg: "{{ mount_check.stdout_lines }}"
      when: mount_check.stdout_lines | length > 0

