---
- name: Ensure basic packages exist on all hosts
  hosts: all
  tasks:
    - ansible.builtin.include_vars:
        file: vault.yml
        name: vault
    - ansible.builtin.include_role:
        name: svwi-users
    - ansible.builtin.include_role:
        name: svwi-basenode
    - ansible.builtin.include_role:
        name: svwi-vault

- name: Make sure vault servers are in compliance with IaC
  hosts: vault-servers
  tasks:
    - ansible.builtin.include_role:
        name: svwi-vault
