---
- name: Configure Data Rig Servers
  hosts: datarig_servers
  become: true
  
  tasks:
    - name: Load vault variables
      ansible.builtin.include_vars:
        file: vault.yml
        name: vault
    
    - name: Include svwi-datarig role
      ansible.builtin.include_role:
        name: svwi-datarig
