- name: Ensure the `admins` group exists
  ansible.builtin.group:
    name: admins
    state: present

- name: Put the `admin-sudo` file in place
  ansible.builtin.copy:
    src: admin-sudo
    dest: /etc/sudoers.d/admin-sudo
    owner: root
    group: root
    mode: '0440'
  register:
    sudoers_file
  notify:
    - Reload sudoers

- name:
  ansible.builtin.include_tasks:
    file: svw-account.yml
  loop: "{{ users }}"
