- name: Restart Landscape client
  ansible.builtin.systemd:
    name: landscape-client
    state: restarted

- name: Update CA certificates
  ansible.builtin.command: >
    update-ca-certificates --fresh
  args:
    warn: false
  when: sentinelagent_result.changed or pro_attach_result.changed
