- name: Restart Landscape client
  ansible.builtin.systemd:
    name: landscape-client
    state: restarted

- name: Update CA certificates
  ansible.builtin.command: >
    update-ca-certificates --fresh
  when: sentinelagent_result.changed or pro_attach_result.changed

- name: Update apt cache
  ansible.builtin.command:
    cmd: apt-get update