---
- name: Render Vault config file (vault.hcl)
  ansible.builtin.template:
    src: config.hcl.j2
    dest: /etc/vault.d/vault.hcl
    mode: '0640'
    owner: root
    group: vault
  notify: Restart Vault Service

- name: Render Vault environment file (vault.env)
  ansible.builtin.template:
    src: vault.env.j2
    dest: /etc/vault.d/vault.env
    mode: '0600'
    owner: vault
  notify: Restart Vault Service

- name: Place balena secrets engine binary
  ansible.builtin.copy:
    src: vault-plugin-secrets-balena
    dest: /opt/vault/plugins/balena
    owner: vault
    group: hashicorp
    mode: '0755'

- name: Place boundary secrets engine binary
  ansible.builtin.copy:
    src: vault-plugin-secrets-boundary
    dest: /opt/vault/plugins/boundary
    owner: vault
    group: hashicorp
    mode: '0755'

- name: Place gcpckms.tpl
  ansible.builtin.copy:
    src: gcpckms.tpl
    dest: /opt/vault/templates/gcpckms.tpl
    owner: vault
    group: hashicorp
    mode: '0644'

- name: Place snapshot-token.tpl
  ansible.builtin.copy:
    src: snapshot-token.tpl
    dest: /opt/vault/templates/snapshot-token.tpl
    owner: vault
    group: hashicorp
    mode: '0644'

- name: Ensure /etc/vault.d/snapshots.token exists and has correct permissions
  ansible.builtin.file:
    path: /etc/vault.d/snapshots.token
    state: touch
    owner: vault
    group: hashicorp
    mode: '0644'

- name: Render take-snapshot.sh script
  ansible.builtin.template:
    src: take-snapshot.sh.j2
    dest: /etc/vault.d/take-snapshot.sh
    owner: vault
    group: vault
    mode: '0700'

- name: Install boundary secrets engine from github release
  ansible.builtin.unarchive:
    src: https://github.com/devops-rob/vault-plugin-boundary-secrets-engine/releases/download/v1.0.2/vault-plugin-boundary-secrets-engine_v1.0.2_linux_amd64.zip
    dest: /opt/vault/plugins
    remote_src: yes
    creates: /opt/vault/plugins/vault-plugin-boundary-secrets-engine_v1.0.2_linux_amd64/vault-plugin-boundary-secrets-engine_v1.0.2_linux_amd64

- name: Place svwi.us wildcard certificate
  ansible.builtin.copy:
    content: "{{ starsvwiuscert }}"
    dest: /etc/vault.d/fullchain.pem
    owner: root
    group: ssl-cert
    mode: '0640'
  when: starsvwiuscert is defined and starsvwiuscert != ''
  notify: Restart Vault Service

- name: Place svwi.us wildcard key
  ansible.builtin.copy:
    content: "{{ starsvwiuskey }}"
    dest: /etc/vault.d/privkey.pem
    owner: root
    group: ssl-cert
    mode: '0640'
  when: starsvwiuskey is defined and starsvwiuskey != ''
  notify: Restart Vault Service

- name: Schedule daily Vault snapshot
  ansible.builtin.cron:
    name: "vault-snapshot"
    minute: "0"
    hour: "6"
    job: "cd /home/vault && bash /etc/vault.d/take-snapshot.sh >> /home/vault/snapshot.log 2>&1"
    user: vault

