---
- name: Ensure hashicorp group exists
  ansible.builtin.group:
    name: hashicorp
    state: present

- name: Add ssl-cert group
  ansible.builtin.group:
    name: ssl-cert
    state: present

- name: Create Vault user
  ansible.builtin.user:
    name: vault
    groups: ssl-cert,hashicorp
    state: present
    append: yes
    home: /home/vault

- name: Install Vault
  ansible.builtin.apt:
    name: vault={{ vault_version | default('1.18.3-1') }}
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure Vault log directory exists
  ansible.builtin.file:
    path: /var/log/vault
    state: directory
    owner: vault
    group: hashicorp
    mode: '0755'

- name: Ensure /opt/vault exists
  ansible.builtin.file:
    path: /opt/vault
    state: directory
    owner: vault
    group: hashicorp
    mode: '0755'

- name: Ensure /opt/vault/templates exists
  ansible.builtin.file:
    path: /opt/vault/templates
    state: directory
    owner: vault
    group: hashicorp
    mode: '0755'

- name: Ensure /opt/vault/plugins exists
  ansible.builtin.file:
    path: /opt/vault/plugins
    state: directory
    owner: vault
    group: hashicorp
    mode: '0755'

- name: Copy vault-profile.sh
  ansible.builtin.copy:
    src: vault-profile.sh
    dest: /etc/profile.d/vault.sh
    owner: root
    mode: '0644'

- name: Start and enable Vault service
  ansible.builtin.systemd:
    name: vault
    state: started
    enabled: yes
    daemon_reload: yes

