---
- name: Deploy Landscape Database Server
  hosts: landscape-server
  tasks:
    - name: Include vault variables
      ansible.builtin.include_vars:
        file: ../vault.yml
        name: vault

    - name: Include svwi-users role
      ansible.builtin.include_role:
        name: svwi-users

    - name: Include svwi-basenode role
      ansible.builtin.include_role:
        name: svwi-basenode

    - name: Include svwi-landscape role
      ansible.builtin.include_role:
        name: svwi-landscape

